esphome:
  name: smartgatewayp1
  friendly_name: smart_gateway_p1
  name_add_mac_suffix: false
  project:
    name: smartgateways.smartmeter
    version: "1.0"

substitutions:
  device_name: smartgatewayp1
  device_description: "Smart Gateways Smart Meter Gateway"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ga1VIxvUly/RGc+xxaJKbxPIt0s6+bXyqvpWUTE7FuE="

ota:
  - platform: esphome
    password: "55ed8162cc46bd09607fc5d9ddcfd7f1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart Gateways Smart Meter"
    password: "smartgateways"

captive_portal:

web_server:
  port: 80

uart:
  baud_rate: 115200
  rx_pin:
    number: GPIO18
    inverted: true
  rx_buffer_size: 3000
#  data_bits: 8
#  parity: NONE
#  stop_bits: 1

# enable the next lines if you want to debug
#  debug:
#    direction: RX
#    after:
#      delimiter: "\r\n"
#    sequence:
#      - lambda: UARTDebug::log_string(direction, bytes);

dsmr:
  max_telegram_length: 3000
  id: dsmr_instance
  receive_timeout: 200ms
# enable the next line if you encounter crc checksum mismatch errors (for some swedish and lithuanian meters)
#  crc_check: false

switch:
  - platform: gpio
    name: "Built-in LED"
    pin: 2
    id: led_wifi_connected

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - if:
              condition:
                api.connected:
              then:
                - switch.turn_on: led_wifi_connected
                - delay: 200ms
                - switch.turn_off: led_wifi_connected
                - delay: 200ms
              else:
                - switch.turn_on: led_wifi_connected
                - delay: 500ms
                - switch.turn_off: led_wifi_connected
                - delay: 500ms
        else:
          - switch.turn_off: led_wifi_connected

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
#    gas_delivered:
#      name: "Gas Consumed"
  - platform: uptime
    name: "SmartMeter Uptime"
  - platform: wifi_signal
    name: "SmartMeter Wi-Fi Signal"
    update_interval: 60s
  
text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
  - platform: wifi_info
    ip_address:
      name: "Smart Gateways SmartMeter IP Address"
    ssid:
      name: "Smart Gateways SmartMeter Wi-Fi SSID"
    bssid:
      name: "Smart Gateways SmartMeter Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: false