# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: sonoffs26_1
  device_friendly_name: SonOff S26 (1)
  device_wifi_name: SonOffS26_1
  device_sampling_time: 60s
  
# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include
    file: boards/esp8266/SonOff_S26.yaml
    vars:
      restorefromflash: true
  settings: !include common/core/settings.yaml

  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 2

captive_portal: !remove
# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  - id: !extend "relay"
    restore_mode: RESTORE_DEFAULT_OFF
