substitutions:
  device_name: "SprinklersSchuur"
  device_id: "sprinklersschuur"
  sprinklers: "Sprinkler Schuur"
  lawn1: "Sprinkler bomen"
  lawn2: "Sprinkler terras"
  run_duration: 1800s
  valve_change_duration: 30s

esphome:
  name: ${device_id}
  friendly_name: ${device_name}

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CkqimbqaB0gvIxnRTpxzSLPH33c00y+1CBMqUxoos+A="

ota:
  - platform: esphome
    password: "c87692c3584919053ef7a0bafda1bfdf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_id}
    password: "0OJc1NhsNYES"

captive_portal:

web_server:
  port: 80
  
sprinkler:
  - id: lawn_sprinkler_ctrlr
    main_switch: "${sprinklers}"
    auto_advance_switch: "${sprinklers} Auto Advance"
    reverse_switch: "${sprinklers} Reverse"
    valve_open_delay: 5s
    pump_start_pump_delay: ${valve_change_duration}  
    pump_stop_valve_delay: ${valve_change_duration}       
    valve_pulse_duration: ${valve_change_duration}  
    valves:
      - valve_switch: ${lawn1}
        enable_switch: "Enable ${lawn1}"
        pump_switch_id: relay5
        run_duration_number:
          id: run_duration_bomen
          name: "Duurtijd ${lawn1}"
          icon: "mdi:timer-outline"
          initial_value: 30
          min_value: 5
          max_value: 90
          unit_of_measurement: min
        valve_on_switch_id: relay2
        valve_off_switch_id: relay1
      - valve_switch: ${lawn2}
        enable_switch: "Enable ${lawn2}"
        pump_switch_id: relay5
        run_duration_number:
          id: run_duration_terras
          name: "Duurtijd ${lawn2}"
          icon: "mdi:timer-outline"
          initial_value: 30
          min_value: 5
          max_value: 90
          unit_of_measurement: min
        valve_on_switch_id: relay4
        valve_off_switch_id: relay3

# Text sensors with general information.
text_sensor:
  # Expose Uptime human readable
  - platform: template
    name: ${device_name} Uptime
    id: ${device_id}_uptime_human
    icon: mdi:clock-start
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${device_name} ESPHome Version

sensor:
# WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    update_interval: 360s
# Uptime sensor.
  - platform: uptime
    id: ${device_id}_uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_id}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_id}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

# 8 relay outputs, exposed as switches in Home Assistant
switch:
  - platform: gpio
    pin: GPIO16
    name: Relay1
    id: relay1
    internal: True
  - platform: gpio
    pin: GPIO14
    name: Relay2
    id: relay2
    internal: True
  - platform: gpio
    pin: GPIO12
    name: Relay3
    id: relay3
    internal: True
  - platform: gpio
    pin: GPIO13
    name: Relay4
    id: relay4
    internal: True
  - platform: gpio
    pin: GPIO15
    name: Pomp
    id: relay5
  - platform: gpio
    pin: GPIO00
    name: Relay6
    id: relay6
  - platform: gpio
    pin: GPIO04
    name: Relay7
    id: relay7
  - platform: gpio
    pin: GPIO05
    name: Relay8
    id: relay8    