# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: sprinklersgrootkot
  device_friendly_name: SprinklersGrootKot
  device_wifi_name: SprinklersGrootKot
  device_sampling_time: 60s
  valve_change_duration: 28s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include boards/esp8266/d1_mini.yaml
  settings: !include common/core/settings.yaml

  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 3

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------
esphome:
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(D8, OUTPUT);
            digitalWrite(D8, HIGH);

i2c:
  sda: GPIO4
  scl: GPIO5

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  - platform: gpio
    name: "Open Valve 1"
    id: relay1
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B0
      number: 8
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Close Valve 1"
    id: relay2
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B1
      number: 9
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Open Valve 2"
    id: relay3
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B2
      number: 10
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Close Valve 2"
    id: relay4
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B3
      number: 11
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Open Valve 3"
    id: relay5
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B4
      number: 12
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Close Valve 3"
    id: relay6
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B5
      number: 13
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 7"
    id: relay7
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B6
      number: 14
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 8"
    id: relay8
    internal: True
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B7
      number: 15
      mode:
        output: true
      inverted: true

# -----------------------------------------------------------------------------
# Sprinklers
# -----------------------------------------------------------------------------
sprinkler:
  - id: lawn_sprinkler_ctrlr
    main_switch: "GrootKot Sprinklers"
    auto_advance_switch: "GrootKot Sprinklers Auto Advance"
    reverse_switch: "GrootKot Sprinklers Reverse"
    valve_open_delay: 5s
    valve_pulse_duration: ${valve_change_duration}  
    valves:
      - valve_switch: "Vogelkooi Lawn"
        enable_switch: "Enable Vogelkooi Lawn"
        run_duration_number:
          id: run_duration_vogelkooi
          name: "Duurtijd Vogelkooi"
          icon: "mdi:timer-outline"
          initial_value: 30
          min_value: 5
          max_value: 90
          unit_of_measurement: min
        valve_on_switch_id: relay1
        valve_off_switch_id: relay2
      - valve_switch: "Haag Lawn"
        enable_switch: "Enable Haag Lawn"
        run_duration_number:
          id: run_duration_haag
          name: "Duurtijd Haag"
          icon: "mdi:timer-outline"
          initial_value: 30
          min_value: 5
          max_value: 90
          unit_of_measurement: min
        valve_on_switch_id: relay3
        valve_off_switch_id: relay4
      - valve_switch: "Zwembad Lawn"
        enable_switch: "Enable Zwembad Lawn"
        run_duration_number:
          id: run_duration_zwembad
          name: "Duurtijd Zwembad"
          icon: "mdi:timer-outline"
          initial_value: 30
          min_value: 5
          max_value: 90
          unit_of_measurement: min
        valve_on_switch_id: relay5
        valve_off_switch_id: relay6
