# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: testwemosheatpipes3
  device_friendly_name: TestWemosHeatpipes3
  device_wifi_name: testwemosheatpipes3
  device_sampling_time: 30s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include
    file: boards/esp8266/d1_mini.yaml
    vars:
      restorefromflash: true
  
  settings: !include common/core/settings.yaml
  
  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 2

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------
i2c: !remove
uart: !remove
spi: !remove

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------
sensor:
  - platform: homeassistant
    id: testsensor
    name: "Temperature Sensor - 5"
    entity_id: sensor.birdcage_temp 
    #internal: false
    on_value: 
      then:
        - logger.log: 
            format: "Value: %.1f"
            args: [ 'id(testsensor).state' ]

  - platform: homeassistant
    id: heatpipesmode
    name: "Heatpipes Mode"
    entity_id: sensor.heatpipes_mode
    #internal: false
    filters:
      - lambda: |-
          if (isnan(x)) {
            return -2;
          } else {
            return x;
          }
      - timeout:
          timeout: 180s
          value: !lambda return -1;
    on_value: 
      then:
        - lambda: |-
              if ((id(heatpipesmode).state) == 0) {
                ESP_LOGD("lambda", "Mode to 0");
              } else if ((id(heatpipesmode).state) == -1) {
                ESP_LOGD("lambda", "Mode to -1");
              } else if ((id(heatpipesmode).state) == -2) {
                ESP_LOGD("lambda", "Mode to -2");
              } else {
                ESP_LOGD("lambda", "Mode to else");
              }
            
switch:
  - platform: gpio
    pin: D1
    name: Relay1
    id: relay1
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: D2
    name: Relay2
    id: relay2
    restore_mode: RESTORE_DEFAULT_ON


  # ESP8266 Software PWM Output
  # https://esphome.io/components/output/esp8266_pwm/
  