# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: testesp32relayboard
  device_friendly_name: TestEsp32RelayBoard
  device_wifi_name: testesp32relayboard
  device_sampling_time: 30s
  valve_run_time: 5s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include boards/esp32/esp32_relay_x16.yaml
  settings: !include common/core/settings.yaml
  
  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 3

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------
#logger:
#  level: DEBUG

# -----------------------------------------------------------------------------
# Components
# -----------------------------------------------------------------------------
one_wire:
  - platform: gpio
    pin: GPIO26
    #id: bus1

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------
sensor:
  # only one device
  - platform: dallas_temp
    id: tempheatpipes
    name: temperatureheatpipes
    update_interval: ${device_sampling_time}
    accuracy_decimals: 1
  #   address: 0x44012212da27cc11
  - platform: homeassistant
    id: heatpipesmode
    name: "Heatpipes Mode"
    entity_id: sensor.heatpipes_mode
    #internal: false
    filters:
      - lambda: |-
          if (isnan(x)) {
            return -2;
          } else {
            return x;
          }
      - timeout:
          timeout: 180s
          value: !lambda return -1;
    on_value: 
      then:
        - lambda: |-
              if ((id(heatpipesmode).state) == 0) {
                ESP_LOGD("lambda", "Mode to 0");
              } else if ((id(heatpipesmode).state) == -1) {
                ESP_LOGD("lambda", "Mode to -1");
              } else if ((id(heatpipesmode).state) == -2) {
                ESP_LOGD("lambda", "Mode to -2");
              } else {
                ESP_LOGD("lambda", "Mode to else");
              }
        - script.execute: modechanged

# -----------------------------------------------------------------------------
# Text Sensors
# -----------------------------------------------------------------------------
text_sensor:
  - platform: template
    name: "Template Text Sensor"
    lambda: |-
        if (id(valve1).current_operation == ValveOperation::VALVE_OPERATION_IDLE) {
           return {"VALVE_OPERATION_IDLE"};
        } else if (id(valve1).current_operation == ValveOperation::VALVE_OPERATION_OPENING) {
           return {"VALVE_OPERATION_IDLE"};
        } else if (id(valve1).current_operation == ValveOperation::VALVE_OPERATION_CLOSING) {
           return {"VALVE_OPERATION_IDLE"};
        }
    update_interval: 60s

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------
binary_sensor:
  # sensor to see if the pellet burner is ready
  - platform: gpio
    pin: GPIO27 #ToDo
    name: "Pellet Burner Ready"
    id: pelletburnerready

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  # motor to feed the radiators
  - platform: gpio
    pin: GPIO25 #ToDo
    name: "Pump Pellet Burner"
    id: pumppelletburner
   
  # motor to feed the radiators
  - platform: gpio
    pin: GPIO23 #ToDo
    name: "Pump Pool"
    id: pumppool   

# -----------------------------------------------------------------------------
# Valves
# -----------------------------------------------------------------------------
valve:
  # valve that switches between the heething system and the vool
  - platform: template
    id: valve1
    name: "Valve 1"
    open_action:
      - script.execute: open_valve1
    close_action:
      - script.execute: close_valve1
    stop_action:
      - script.execute: stop_valve1

  # valve that switches between the heathing and the hot water
  - platform: template
    id: valve2
    name: "Valve 2"
    open_action:
      - script.execute: open_valve2
    close_action:
      - script.execute: close_valve2
    stop_action:
      - script.execute: stop_valve2

  # valve that switches between the solar panels and the pellet burner
  - platform: template
    id: valve3
    name: "Valve 3"
    open_action:
      - script.execute: open_valve3
    close_action:
      - script.execute: close_valve3
    stop_action:
      - script.execute: stop_valve3


# -----------------------------------------------------------------------------
# Scripts
# -----------------------------------------------------------------------------
script:
  - id: open_valve1
    then:
      - script.stop: close_valve1
      - switch.turn_on: relay01
      - delay: ${valve_run_time}
      - switch.turn_off: relay01
      - valve.template.publish:
          id: valve1
          state: OPEN
  - id: close_valve1
    then:
      - script.stop: open_valve1
      - switch.turn_on: relay02
      - delay: ${valve_run_time}
      - switch.turn_off: relay02      
      - valve.template.publish:
          id: valve1
          state: CLOSED
  - id: stop_valve1
    then:
      - script.stop: close_valve1
      - script.stop: open_valve1
      - switch.turn_off: relay01
      - switch.turn_off: relay02

  - id: open_valve2
    then:
      - script.stop: close_valve2
      - switch.turn_on: relay03
      - delay: ${valve_run_time}
      - switch.turn_off: relay03
      - valve.template.publish:
          id: valve2
          state: OPEN
  - id: close_valve2
    then:
      - script.stop: open_valve2
      - switch.turn_on: relay04
      - delay: ${valve_run_time}
      - switch.turn_off: relay04     
      - valve.template.publish:
          id: valve2
          state: CLOSED
  - id: stop_valve2
    then:
      - script.stop: close_valve2
      - script.stop: open_valve2
      - switch.turn_off: relay03
      - switch.turn_off: relay04

  - id: open_valve3
    then:
      - script.stop: close_valve3
      - switch.turn_on: relay05
      - delay: ${valve_run_time}
      - valve.template.publish:
          id: valve3
          state: OPEN
  - id: close_valve3
    then:
      - script.stop: open_valve3
      - switch.turn_off: relay05
      - delay: ${valve_run_time}
      - valve.template.publish:
          id: valve3
          state: CLOSED
  - id: stop_valve3
    then:
      - script.stop: close_valve3
      - script.stop: open_valve3
      - switch.turn_off: relay05

  - id: modechanged
    mode: restart
    then:
      - delay: 1s