# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: wemoskelder
  device_friendly_name: Wemos Kelder
  device_wifi_name: WemosKelder
  device_sampling_time: 60s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include
    file: boards/esp8266/d1_mini.yaml
    vars:
      restorefromflash: true
  settings: !include common/core/settings.yaml

  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 3

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------
# status_led: !remove
i2c: !remove
uart: !remove
spi: !remove
one_wire:
  - platform: gpio
    pin: GPIO04

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------
sensor:
  - platform: dallas_temp
    name: WwIn
    index: 0
#    address: 0x28CDF24592150247
    update_interval: ${device_sampling_time}
  - platform: dallas_temp
    name: WwOut
    index: 1
#    address: 0x28A77A4592180237
    update_interval: ${device_sampling_time}

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  - platform: gpio
    id: pump
    name: "Pump"
    pin: GPIO16
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

# -----------------------------------------------------------------------------
# Time
# -----------------------------------------------------------------------------
time:
  - platform: sntp
    id: my_time
    timezone: "Europe/Brussels" # Set your timezone
    on_time:
      - seconds: 0
        minutes: 0
        hours: 9
        days_of_week: MON-SUN
        then:
          - switch.turn_on: pump
      - seconds: 0
        minutes: 0
        hours: 18
        days_of_week: MON-SUN
        then:
          - switch.turn_off: pump
