# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: wemosberging
  device_friendly_name: WemosBerging
  device_wifi_name: WemosBerging
  device_sampling_time: 60s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include boards/esp8266/esp01_1m.yaml
  settings: !include common/core/settings.yaml

  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  # webserver: !include
  #   file: common/network/webserver.yaml
  #   vars:
  #     version: 2

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------
# status_led: !remove
# i2c: !remove
# uart: !remove
# spi: !remove

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------
sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Berging Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Berging Humidity"
      accuracy_decimals: 1
    update_interval: 60s

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  - platform: gpio
    name: "Fan"
    pin: GPIO5