esphome:
  name: wemos-barn
  friendly_name: Wemos Barn

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NLOQTgpq6CnCwZdEK2nkRD/LDmzYapUBvyiSdtu7awA="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos-Barn Fallback Hotspot"
    password: "TsQN0sUvR9SF"

captive_portal:

web_server:
  port: 80

# Text sensors with general information.
text_sensor:
  # Expose Uptime human readable
  - platform: template
    name: Wemos Barn Uptime
    id: wemos_barn_uptime_human
    icon: mdi:clock-start
  # Expose ESPHome version as sensor.
  - platform: version
    name: Wemos Barn ESPHome Version

sensor:
# WiFi Signal sensor.
  - platform: wifi_signal
    name: Wemos Barn WiFi Signal
    update_interval: 360s
# Uptime sensor.
  - platform: uptime
    id: wemos_barn_uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: wemos_barn_uptime_human
            state: !lambda |-
              int seconds = round(id(wemos_barn_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Outdoor Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Outdoor Humidity"
      accuracy_decimals: 1
    update_interval: 60s
