# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: wemosbarn
  device_friendly_name: Wemos Barn
  device_wifi_name: WemosBarn
  device_sampling_time: 60s
  
# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include boards/esp8266/d1_mini_pro.yaml
  settings: !include common/core/settings.yaml

  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 3

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------
status_led: !remove
i2c: !remove
uart: !remove
spi: !remove

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------
sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Outdoor Temperature"
      accuracy_decimals: 1
    humidity:
      name: "Outdoor Humidity"
      accuracy_decimals: 1
    update_interval: 60s
