#Wemos + MCP23017 + 8x relay board
esphome:
  name: wemos-test
  friendly_name: Wemos Test

  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            pinMode(D8, OUTPUT);
            digitalWrite(D8, HIGH);

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "JZEcbtqQjJYLdQp+GEunAQ/jnn0t0sp5nkaDJJlgh8Q="

ota:
  - platform: esphome
    password: "ba0e3053587dc879f1f8e21dc2268891"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos-Test Fallback Hotspot"
    password: "T2w1S8kUwJ4o"

captive_portal:

web_server:

i2c:
  sda: GPIO4
  scl: GPIO5

# Text sensors with general information.
text_sensor:
  # Expose Uptime human readable
  - platform: template
    name: Wemos Barn Uptime
    id: wemos_barn_uptime_human
    icon: mdi:clock-start
  # Expose ESPHome version as sensor.
  - platform: version
    name: Wemos Barn ESPHome Version

sensor:
# WiFi Signal sensor.
  - platform: wifi_signal
    name: Wemos Barn WiFi Signal
    update_interval: 360s
# Uptime sensor.
  - platform: uptime
    id: wemos_barn_uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: wemos_barn_uptime_human
            state: !lambda |-
              int seconds = round(id(wemos_barn_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x20

switch:
  - platform: gpio
    name: "Relay 1"
    id: relay1
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B0
      number: 8
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 2"
    id: relay2
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B1
      number: 9
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 3"
    id: relay3
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B2
      number: 10
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 4"
    id: relay4
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B3
      number: 11
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 5"
    id: relay5
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B4
      number: 12
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 6"
    id: relay6
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B5
      number: 13
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 7"
    id: relay14
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B6
      number: 14
      mode:
        output: true
      inverted: true

  - platform: gpio
    name: "Relay 8"
    id: relay15
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin B7
      number: 15
      mode:
        output: true
      inverted: true
