# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: testes32s
  device_friendly_name: testes32s
  device_wifi_name: testes32s
  device_sampling_time: 30s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include boards/esp32/esp32s.yaml
  settings: !include common/core/settings.yaml

  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include
    file: common/network/webserver.yaml
    vars:
      version: 3
  bluetooth: !include common/network/bluetooth_tracker.yaml

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Output
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Switchs
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Lights
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Scripts
# -----------------------------------------------------------------------------

esp32_ble_tracker:

ble_client:
  - mac_address: 28:68:47:EA:05:2F
    id: itag_black
    auto_connect: true