esphome:
  name: p1-power-meter
  friendly_name: P1 Power Meter

esp8266:
  board: d1_mini

logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "dD9xgb2er/7Zcvi+7HtFjQ9HZOFUCLpDyUckmBvyNow="

ota:
  - platform: esphome
    password: "58786df4eb2b39dd9db89a5aba668028"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "P1-Power-Meter Fallback Hotspot"
    password: "c9CxPv9TITR8"

captive_portal:

# Enable Web server.
web_server:
  port: 80

uart:
    id: uart_bus
    rx_pin:
      number: 3
#      inverted: true
    baud_rate: 115200
    rx_buffer_size: 1500

# Text sensors with general information.
text_sensor:
  # Expose Uptime human readable
  - platform: template
    name: Digitale Meter Uptime
    id: digitale_meter_uptime_human
    icon: mdi:clock-start
  # Expose ESPHome version as sensor.
  - platform: version
    name: Digitale Meter ESPHome Version

sensor:

# WiFi Signal sensor.
  - platform: wifi_signal
    name: Digitale Meter WiFi Signal
    update_interval: 360s
# Uptime sensor.
  - platform: uptime
    id: digitale_meter_uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: digitale_meter_uptime_human
            state: !lambda |-
              int seconds = round(id(digitale_meter_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

# Sensoren van P1 Smart meter
  - platform: dsmr
    energy_delivered_tariff1:
      name: energy_delivered_tariff1
      filters:
        - throttle: 15s
    energy_delivered_tariff2:
      name: energy_delivered_tariff2
      filters:
        - throttle: 15s
    energy_returned_tariff1:
      name: energy_returned_tariff1
      filters:
        - throttle: 15s
    energy_returned_tariff2:
      name: energy_returned_tariff2
      filters:
        - throttle: 15s
    power_delivered:
      name: power_delivered
      filters:
        - throttle: 15s
    power_returned:
      name: power_returned
      filters:
        - throttle: 15s
    electricity_failures:
      name: electricity_failures
      filters:
        - throttle: 360s
    electricity_long_failures:
      name: electricity_long_failures
      filters:
        - throttle: 360s
    voltage_l1:
      name: voltage_l1
      filters:
        - throttle: 120s
    current_l1:
      name: current_l1
      filters:
        - throttle: 120s
