substitutions:
  device_name: "Test Sprinkler"
  device_id: "test-sprinkler"

esphome:
  name: ${device_id}
  friendly_name: ${device_name}

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "V5vbPWXBbGyJiH97whMKyxhT5Ue6BY9iOfnJFbmC4TY="

ota:
  - platform: esphome
    password: "2f7b3b2817933c440497982b5ffa8b5d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Sprinkler Fallback Hotspot"
    password: "FkqKM0z5QCgW"

captive_portal:

web_server:
