esphome:
  name: testwemosheatpipes
  friendly_name: TestWemosHeatpipes

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "c6b4d57094142d532266cd75f46d1248"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testwemosheatpipes"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# Example configuration entry
sensor:
  - platform: homeassistant
    id: testsensor
    name: "Temperature Sensor From Home Assistant"
    entity_id: sensor.birdcage_temp 
    on_raw_value: 
      then:
        - logger.log: 
            format: "RawValue: %.1f"
            args: [ 'id(testsensor)' ]        
    on_value: 
      then:
        - logger.log: 
            format: "Value: %.1f"
            args: [ 'id(testsensor)' ]
            
debug:
  update_interval: 5s

