esphome:
  name: test123
  friendly_name: Test123

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EQdrGzYuBjM3PfzIN6ceiQ9QjS7q2auAXZvS6C5z6xk="

ota:
  - platform: esphome
    password: "d206c1c26bca67dffff8abda68c54ecd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test123 Fallback Hotspot"
    password: "Lqo6Jnk2e4v0"

captive_portal:
    