# -----------------------------------------------------------------------------
# Substitution Variables
# -----------------------------------------------------------------------------
substitutions:
  device_internal_name: testwemosheatpipes2
  device_friendly_name: TestWemosHeatpipes2
  device_wifi_name: testwemosheatpipes2
  device_sampling_time: 30s

# -----------------------------------------------------------------------------
# Common Packages
# -----------------------------------------------------------------------------
packages:
  # ---------------------------------------------------------------------------
  # Board
  # ---------------------------------------------------------------------------
  board: !include boards/esp8266/d1_mini.yaml
  settings: !include common/core/settings.yaml
  
  # ---------------------------------------------------------------------------
  # Network
  # ---------------------------------------------------------------------------
  wifi: !include common/network/wifi.yaml
  webserver: !include common/network/webserver.yaml

# -----------------------------------------------------------------------------
# Custom Device Configuration
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Sensors
# -----------------------------------------------------------------------------
sensor:
  - platform: homeassistant
    id: testsensor
    name: "Temperature Sensor From Home Assistant - 2"
    entity_id: sensor.birdcage_temp 
    #internal: false
    on_value: 
      then:
        - logger.log: 
            format: "Value: %.1f"
            args: [ 'id(testsensor).state' ]

  - platform: homeassistant
    id: heatpipesmode
    name: "Heatpipes Mode"
    entity_id: sensor.heatpipes_mode
    #internal: false
    filters:
      - lambda: |-
          if (isnan(x)) {
            return -2;
          } else {
            return x;
          }
      - timeout:
          timeout: 180s
          value: !lambda return -1;
    on_value: 
      then:
        - lambda: |-
              if ((id(heatpipesmode).state) == 0) {
                ESP_LOGD("lambda", "Mode to 0");
              } else if ((id(heatpipesmode).state) == -1) {
                ESP_LOGD("lambda", "Mode to -1");
              } else if ((id(heatpipesmode).state) == -2) {
                ESP_LOGD("lambda", "Mode to -2");
              } else {
                ESP_LOGD("lambda", "Mode to else");
              }
            
