defaults:
  restorefromflash: false

esp8266:
  board: esp01_1m
  framework:
    version: latest
  restore_from_flash: ${restorefromflash}

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------
binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  - platform: gpio
    pin: GPIO12
    id: "relay"
    name: "Relay"
