defaults:
  restorefromflash: false

esp8266:
  board: esp01_1m
  framework:
    version: latest
  restore_from_flash: ${restorefromflash}

# -----------------------------------------------------------------------------
# Binary Sensors
# -----------------------------------------------------------------------------
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
#   - platform: status
#     name: "Status"

# -----------------------------------------------------------------------------
# Switches
# -----------------------------------------------------------------------------
switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: "relay"
#   - platform: restart
#     name: "sonoffs26_1 Restart"   