###############################################################################
# WIFI
###############################################################################
wifi:
  min_auth_mode: WPA2
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      
  ap:
    ssid: ${device_wifi_name}
    password: !secret ap_password
    ap_timeout: 180s

captive_portal:

###############################################################################
# Sensors
###############################################################################
sensor:
  - platform: wifi_signal
    id: ${device_internal_name}_wifi_signal_db
    name: WiFi Signal dB
    icon: mdi:wifi
    update_interval: ${device_sampling_time}

###############################################################################
# Text Sensors
###############################################################################
text_sensor:
  # Wifi internal sensors
  - platform: wifi_info
    ip_address:
      id: ${device_internal_name}_ip_address
      name: IP Address
      icon: mdi:ip-network
    ssid:
      id: ${device_internal_name}_connected_ssid
      name: Connected SSID
      icon: mdi:access-point
    mac_address:
      id: ${device_internal_name}_mac_address
      name: Mac Address
      icon: mdi:network-outline
    dns_address:
      id: ${device_internal_name}_dns_address
      name: DNS Address
      icon: mdi:dns
